// eslint-config-next 16 ships flat configs directly, so the FlatCompat shim
// that this file used under v15 is no longer needed.
import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const eslintConfig = [
  {
    ignores: [".next/**", ".open-next/**", ".wrangler/**", "node_modules/**"],
  },
  ...coreWebVitals,
  ...typescript,
  {
    // Generated by `wrangler types`; it already disables ESLint at the top but
    // is skipped here so a regenerated file never fails lint.
    ignores: ["cloudflare-env.d.ts"],
  },
];

export default eslintConfig;
