// Bindings that never appear in the generated cloudflare-env.d.ts because they
// are Workers secrets rather than wrangler.jsonc `vars`.
//
// This file intentionally has no imports/exports so that the interface merges
// with the global CloudflareEnv generated by `npm run cf:typegen`.
interface CloudflareEnv {
  /** HMAC key used to sign session cookies. `wrangler secret put SESSION_SECRET` */
  SESSION_SECRET: string;
}
