-- D1 (SQLite) port of supabase/001_create_assembly_members.sql.
--
-- Type mapping notes:
--   uuid        -> text        (ids are generated by scripts/csv-to-d1-seed.mjs)
--   jsonb       -> text        (JSON kept as a string, parsed in the app)
--   timestamptz -> text        (datetime('now') is UTC in SQLite)
--   smallint    -> integer     (SQLite has a single integer type)
--
-- Row Level Security has no D1 equivalent. D1 is only reachable through the
-- Worker binding, so access control lives in lib/db/assembly-members.ts.

create table if not exists assembly_members (
  id text primary key,
  source_pdf_name text,
  source_page integer,
  source_row_number integer,
  province_code integer,
  province_name text,
  electoral_unit_number integer,
  electoral_unit_description text,
  full_name text not null,
  full_name_ascii text,
  birth_date_text text,
  birth_year integer,
  gender text,
  nationality text,
  ethnicity text,
  religion text,
  home_town text,
  residence text,
  general_education text,
  professional_qualification text,
  political_theory text,
  foreign_language text,
  occupation_position text,
  workplace text,
  party_joined_on text,
  national_assembly_history text,
  peoples_council_history text,
  notes text,
  raw_text text,
  source_data text not null default '{}',
  term_number integer not null default 16,
  term_label text not null default 'Vietnam National Assembly Term 16',
  -- Lowercased, diacritic-folded haystack for search. Postgres used ILIKE,
  -- but SQLite's LIKE/lower() only fold ASCII, so the folding is precomputed
  -- at import time and the query folds its input the same way.
  search_text text not null default '',
  -- Sort keys, folded the same way. SQLite only has BINARY collation, which
  -- orders UTF-8 by byte value: "THANH PHO HUE" would sort before
  -- "THANH PHO HA NOI" because U+0055 < U+00C0. Postgres used a linguistic
  -- collation, so the folded values keep the ordering users expect.
  full_name_sort text not null default '',
  province_sort text not null default '',
  created_at text not null default (datetime('now'))
);

create index if not exists assembly_members_full_name_idx
  on assembly_members (full_name);

create index if not exists assembly_members_full_name_ascii_idx
  on assembly_members (full_name_ascii);

create index if not exists assembly_members_full_name_sort_idx
  on assembly_members (full_name_sort);

create index if not exists assembly_members_province_name_idx
  on assembly_members (province_name);

create index if not exists assembly_members_province_sort_idx
  on assembly_members (province_sort);

create index if not exists assembly_members_electoral_unit_number_idx
  on assembly_members (electoral_unit_number);
