#!/usr/bin/env python3
"""Build d1/seed.sql from data/import/assembly_members.csv.

Usage:
  python3 scripts/build_d1_seed.py

Reads the CSV produced by scripts/extract_assembly_members.py and emits a
single SQL file of batched INSERT statements. Each row gets a generated UUID
so the output is deterministic-looking but rows are independent of any
external service.
"""

import csv
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "data" / "import" / "assembly_members.csv"
OUTPUT_PATH = ROOT / "d1" / "seed.sql"

COLUMNS = [
    "source_pdf_name",
    "source_page",
    "source_row_number",
    "province_code",
    "province_name",
    "electoral_unit_number",
    "electoral_unit_description",
    "full_name",
    "full_name_ascii",
    "birth_date_text",
    "birth_year",
    "gender",
    "nationality",
    "ethnicity",
    "religion",
    "home_town",
    "residence",
    "general_education",
    "professional_qualification",
    "political_theory",
    "foreign_language",
    "occupation_position",
    "workplace",
    "party_joined_on",
    "national_assembly_history",
    "peoples_council_history",
    "notes",
    "raw_text",
    "source_data",
    "term_number",
    "term_label",
]

INT_COLUMNS = {
    "source_page",
    "source_row_number",
    "province_code",
    "electoral_unit_number",
    "birth_year",
    "term_number",
}


def sql_literal(value: str) -> str:
    if value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def build_row(row: dict) -> str:
    id_value = "'" + str(uuid.uuid4()) + "'"
    values = [id_value]
    for col in COLUMNS:
        raw = row.get(col, "")
        if col in INT_COLUMNS:
            if raw == "" or raw.strip() == "":
                values.append("NULL")
            else:
                try:
                    values.append(str(int(raw)))
                except ValueError:
                    values.append(sql_literal(raw))
        elif col == "source_data":
            values.append(sql_literal(raw) if raw else "'{}'")
        else:
            values.append(sql_literal(raw))
    return "(" + ", ".join(values) + ")"


def main() -> None:
    if not CSV_PATH.exists():
        raise SystemExit(f"Missing CSV: {CSV_PATH}")

    with CSV_PATH.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        rows = [build_row(row) for row in reader]

    if not rows:
        raise SystemExit("CSV has no data rows")

    batch_size = 10
    lines = [
        "-- Generated by scripts/build_d1_seed.py from data/import/assembly_members.csv",
        "-- Do not edit by hand. Regenerate with: python3 scripts/build_d1_seed.py",
        "-- Apply with: wrangler d1 execute vn-politician-db --file d1/seed.sql [--remote]",
        "",
    ]
    for start in range(0, len(rows), batch_size):
        batch = rows[start : start + batch_size]
        lines.append(
            "insert into assembly_members (id, "
            + ", ".join(COLUMNS)
            + ") values\n"
            + ",\n".join(batch)
            + ";"
        )

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()